### ISSUE TITLE
Single page display

### ISSUE THREAD

**Issue by AldrinAJ** [prasetiyo28/flipbook-codeigniter#2]
Hi @prasetiyo28 , It is an "Awesome" work. Are you still supporting this project?

**Comment by AldrinAJ** [comment]
https://github.com/RaffaeleMorganti/pdf-viewer
I followed the above and got some ideas..

and @prasetiyo28 , thanks for the wonderful work and the idea.

**Comment by prasetiyo28** [comment]
> https://github.com/RaffaeleMorganti/pdf-viewer
> I followed the above and got some ideas..
> 
> and @prasetiyo28 , thanks for the wonderful work and the idea.

thans too , i hope you got an awesome idea too
